---
- name: Add browsers
  homebrew_cask:
    name:
      - firefox
      - google-chrome
      - opera
    state: present
  when: ansible_os_family == 'Darwin'
  tags: common

- name: Add desktop utility tools
  homebrew_cask:
    name:
      - cloak
      - dash
      - alfred
      - flux
      - cleanmymac
      - caffeine
      - airfoil
      - smcfancontrol
      - gpgtools
      - keybase
      - java
      - handbrake
    state: present
  when: ansible_os_family == 'Darwin'
  tags: common

- name: Add general desktop tools
  homebrew_cask:
    name:
      - iterm2
      - libreoffice
      - balsamiq-mockups
      - airfoil
      - dropbox
      - google-drive
      - send-to-kindle
      - skype
      - transmit
      - keepassx
      - fluid
    state: present
  when: ansible_os_family == 'Darwin'
  tags: common

- name: Add screenshots directory
  file:
      path: "~/Desktop/Screenshots"
      state: directory
  when: ansible_os_family == 'Darwin'
  tags:
    - common
    - macos

- name: Get current screenshot directory
  command: defaults read com.apple.screencapture location
  register: current_screenshot_directory
  when: ansible_os_family == 'Darwin'
  tags:
    - common
    - macos

