---
- name: install vim (Mac)
  homebrew:
    name: 
      - vim
    state: present
  when: ansible_os_family == 'Darwin'
  tags: vim

- name: tap neovim (Mac)
  homebrew_tap:
    name: neovim/neovim
    state: present
  when: ansible_os_family == 'Darwin'
  tags: vim

- name: install neovim (Mac)
  homebrew:
    name:
      - neovim
    state: present
  when: ansible_os_family == 'Darwin'
  tags: vim

- name: install vim (Ubuntu)
  apt: pkg=vim state=present
  when: ansible_os_family == 'Ubuntu'
  tags: vim

- name: add vim autoload dir
  file:
    name: ~/.vim/autoload
    state: directory
    recurse: yes
  tags: vim

- name: add vim bundle dir
  file:
    name: ~/.vim/bundle
    state: directory
    recurse: yes
  tags: vim

- name: install Pathogen
  copy:
    src: pathogen-24.vim
    dest: ~/.vim/autoload/pathogen.vim
  tags: vim

- name: add vimrc
  copy: src=basic.vim dest=~/.vimrc
  tags: vim

- name: install vim plugins
  git: repo={{ item.repo}} dest=~/.vim/bundle/{{ item.name }}
  with_items:
    - { repo: "https://github.com/scrooloose/nerdtree.git", name: "nerdtree", force: "yes" }
    - { repo: "https://github.com/ctrlpvim/ctrlp.vim.git", name: "ctrlp", force: "yes" }
    - { repo: "https://github.com/vim-syntastic/syntastic.git", name: "syntastic", force: "yes" }
    - { repo: "https://github.com/altercation/vim-colors-solarized.git", name: "solarized", force: "yes" }
    - { repo: "https://github.com/nvie/vim-flake8.git", name: "flake8", force: "yes" }
    - { repo: "https://github.com/davidhalter/jedi-vim.git", name: "jedi-vim", force: "yes" }
    - { repo: "https://github.com/jremmen/vim-ripgrep", name: "vim-ripgrep", force: "yes" }
  tags: vim
